### ISSUE TITLE
Cannot read property 'route' of undefined

### ISSUE THREAD

**Issue by bigbassroller** [bigbassroller/isomorphic-js#1]
See on "cannot-read-route-undefined" branch. On page 91 of the book and getting this error:
```
      this.options.server.route({
                         ^

TypeError: Cannot read property 'route' of undefined
    at Application.addRoute (/Users/Bigbassroller/Sites/isomorphic-js/dist/lib/index.js:31:26)
    at Application.registerRoutes (/Users/Bigbassroller/Sites/isomorphic-js/dist/lib/index.js:23:14)
    at new Application (/Users/Bigbassroller/Sites/isomorphic-js/dist/lib/index.js:16:10)
    at Object.<anonymous> (/Users/Bigbassroller/Sites/isomorphic-js/dist/index.js:21:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
```

**Comment by bigbassroller** [comment]
Issue has gone away after re coding.
